baseURL = "https://amassmetals.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = "Amass Metals"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
name = "Be a Founder"
URL = "https://forms.office.com/Pages/ResponsePage.aspx?id=l1JPWmptT0OgPYcHAnD5cslOLnYDd4NPldkEoxDeIQhUQTRLOUFPNzkyWFgyV1AwVEtGVDlIWkhMSS4u"
weight = 2
[[menu.main]]
name = "twitter"
url = "https://twitter.com/AmassMetals"
weight = 3
[params]
author = "Themefisher"
description = "This is meta description"
googleAnalitycsID = 216100421
home = "Home"
logo = "images/logo.png"
# fallback image
image = "images/amassmetals.png"
[params.contact]
enable = true
formAction = "#"
[params.footer]
address = "125/A, CA Commercial Area, California, USA"
email = "steve.fruits@email.com"
phone = "+880 2544 658 256"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
